name: Generate Datas

on:
  # Executa às 00:00 e às 12:00 todos os dias
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-datas:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    # Se você for usar o GITHUB_TOKEN padrão (em vez de um PAT), precisa de permissão de escrita:
    # permissions:
    #   contents: write

    steps:
      # Gera a animação (Snake)
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ViniciusProvasi
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publica o resultado na branch "output"
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          # Aqui você utiliza um Personal Access Token (PAT) que você criou
          # e adicionou como secret "ACTIONS_PAT" em Settings > Secrets and variables > Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions:
  contents: write
